development:
  adapter: postgresql
  database: FedBrand_development
  host: localhost

test:
  adapter: postgresql
  database: FedBrand_test
  host: localhost

production:
  adapter: postgresql
  database: FedBrand_production
  host: localhost