development:
  adapter: postgresql
  database: FedBrand_development
test:
  adapter: postgresql
  database: FedBrand_test
  host: localhost
production:
  adapter: postgresql
  database: FedBrand_production
